teaching_team = ["mac-wang", "jon-lee", "allen_wr"] # jaccounts

maxsize = 5 # 5MB repo max size
releasetags = ["h1", "h2", "h3"] # list of valid release tags 

[files]
immutable = [".gitignore", ".gitattributes", ".gitea/workflows/push.yaml"] # readonly files
required = [ "Changelog.md", "Readme.md" ] # files that must be found
whitelist.patterns = ["*.cpp", "*.c", "*.m", "*.md", "Makefile", "CMakelist.txt", ".gitea", "messenger.json"] # files/patterns which are not  forbidden