name: build
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: https://gitea.com/BoYanZh/checkout@focs
      - name: Display Python3 version
        run: python3 --version
      - name: Install PDM
        run: |
          echo curl
          curl -sSL https://ghfast.top/https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py -o install-pdm.py
          echo sed
          sed -i 's|https://github.com|https://ghfast.top/https://github.com|g' install-pdm.py
          echo python3
          python3 install-pdm.py -p /usr
      - name: Display PDM version
        run: pdm --version
      - name: PDM install dependencies
        run: |
          pdm install
      - name: Lint
        run: |
          pdm run lint
      - name: Test
        run: |
          pdm run test
      - name: Run
        run: |
          pdm run app --help
